import json, io, os

SCRATCH = os.path.dirname(os.path.abspath(__file__))
lib = json.load(open(os.path.join(SCRATCH, "routes-lib.json")))
GAME = r"c:\Users\Ant\Documents\Claude\Projects\Uber Eats Build\uber-eats-minigames\Multi-View-Screen\route-picker.html"
src = io.open(GAME, encoding="utf-8").read()
i1 = src.index("const canvas = document.getElementById('game');")
i2 = src.index("function backToTown(){")
head, tail = src[:i1], src[i2:]

engine = r"""const canvas = document.getElementById('game');
const ctx = canvas.getContext('2d');

/* ======================================================================
   PATH PICKER v3 - real street-map edition.
   One OSM-derived artwork (pathmap.png, attribution baked in). Route pairs
   are pre-generated by pathfinding over the map's actual street network,
   so every line follows real drawn streets. Each round zooms the viewport
   to its route pair. Difficulty bands E/M/H/X (length gap shrinks) plus a
   shrinking decision timer -> a run always ends; score = base + speed
   bonus so totals spread for clean leaderboard ranking.
   ====================================================================== */

const MAPW = 1260, MAPH = 1548;
const mapImg = new Image(); mapImg.src = 'pathmap.png?v=1';
let mapReady = false; mapImg.onload = () => { mapReady = true; };

const LIB = __LIB__;

const COL = { A:'#2997ff', B:'#ff3ea5', good:'#019147', bad:'#ff4d4d' };
const DRAW_MS = 520;
const REVEAL_OK = 1250, REVEAL_BAD = 1650;
const Q = new URLSearchParams(location.search);
const DEBUG = Q.get('debug') === '1';

function bandFor(r){ return r <= 3 ? 'E' : r <= 6 ? 'M' : r <= 9 ? 'H' : 'X'; }
function roundTime(r){ const tier = Math.floor((r - 1) / 3); return Math.max(1700, Math.round(4800 * Math.pow(0.78, tier))); }

let state = 'idle';
let score = 0, best = +(localStorage.getItem('routerush_best_v2') || 0);
let lives = 3, streak = 0, round = 0;
let timeLeft = 0, timeMax = 1, drawT = 0, revealT = 0, revealDur = 1;
let lastResult = null, chosen = null;
let bestStreak = +(localStorage.getItem('routerush_beststreak') || 0);
let stats = { answers: 0, correct: 0, rtSum: 0, picks: 0 };
let muted = localStorage.getItem('pathpicker_muted') === '1';
const popups = [], particles = [];
let flash = null, shake = 0;
let reduceMotion = false; try { reduceMotion = matchMedia('(prefers-reduced-motion: reduce)').matches; } catch (e) {}

const queues = {};
function drawFrom(band){
  if (!queues[band] || !queues[band].length){
    queues[band] = LIB[band].map((_, i) => i);
    for (let i = queues[band].length - 1; i > 0; i--){ const j = Math.floor(Math.random() * (i + 1)); const t = queues[band][i]; queues[band][i] = queues[band][j]; queues[band][j] = t; }
  }
  return LIB[band][queues[band].pop()];
}

let cur = null;
function cumlen(pts){
  const c = [0];
  for (let i = 1; i < pts.length; i++) c.push(c[i-1] + Math.hypot(pts[i][0]-pts[i-1][0], pts[i][1]-pts[i-1][1]));
  return c;
}
function pointAtFrac(route, f){
  const target = Math.max(0, Math.min(1, f)) * route.cum[route.cum.length - 1];
  const pts = route.pts, cum = route.cum;
  for (let i = 1; i < cum.length; i++){
    if (cum[i] >= target){
      const seg = cum[i] - cum[i-1] || 1;
      const t = (target - cum[i-1]) / seg;
      return { x: pts[i-1][0] + (pts[i][0]-pts[i-1][0]) * t,
               y: pts[i-1][1] + (pts[i][1]-pts[i-1][1]) * t,
               ang: Math.atan2(pts[i][1]-pts[i-1][1], pts[i][0]-pts[i-1][0]) };
    }
  }
  const n = pts.length - 1;
  return { x: pts[n][0], y: pts[n][1], ang: 0 };
}
function newRound(){
  round++;
  const band = bandFor(round);
  const rd = drawFrom(band);
  const swap = Math.random() < 0.5;
  const mk = pts => ({ pts: pts, cum: cumlen(pts) });
  const A = mk(swap ? rd.long : rd.short), B = mk(swap ? rd.short : rd.long);
  const correct = swap ? 'B' : 'A';
  const all = rd.short.concat(rd.long);
  let x0 = Math.min.apply(null, all.map(p => p[0])), x1 = Math.max.apply(null, all.map(p => p[0]));
  let y0 = Math.min.apply(null, all.map(p => p[1])), y1 = Math.max.apply(null, all.map(p => p[1]));
  const padPx = 55;
  x0 -= padPx; x1 += padPx; y0 -= padPx; y1 += padPx;
  const AR = win.w / win.h;
  let w = x1 - x0, h = y1 - y0;
  if (w / h > AR){ const nh = w / AR; y0 -= (nh - h) / 2; h = nh; } else { const nw = h * AR; x0 -= (nw - w) / 2; w = nw; }
  if (w > MAPW){ const s = MAPW / w; w = MAPW; h = h * s; }
  if (h > MAPH){ const s = MAPH / h; h = MAPH; w = w * s; }
  x0 = Math.max(0, Math.min(MAPW - w, x0));
  y0 = Math.max(0, Math.min(MAPH - h, y0));
  cur = { A: A, B: B, correct: correct, band: band, view: { sx: x0, sy: y0, sw: w, sh: h } };
  drawT = 0; chosen = null; lastResult = null;
  timeMax = roundTime(round); timeLeft = timeMax;
  state = 'draw';
  setButtons(false); showPrompt(false);
  updateHUD();
}

let dpr = 1, cssW = 0, cssH = 0, HUD_TOP = 138;
const PAD = 14;
let win = { x: 0, y: 0, w: 300, h: 380 };
function layout(){
  dpr = Math.min(window.devicePixelRatio || 1, 2);
  cssW = canvas.clientWidth; cssH = canvas.clientHeight;
  canvas.width = Math.round(cssW * dpr); canvas.height = Math.round(cssH * dpr);
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  const pr = document.getElementById('prompt');
  if (pr){ const r = pr.getBoundingClientRect(); if (r.height > 0) HUD_TOP = Math.max(120, Math.round(r.bottom) + 10); }
  const btnH = Math.min(59, Math.max(41, 0.06 * cssH));
  const availW = cssW - PAD * 2;
  const availH = cssH - HUD_TOP - (btnH + 42);
  win = { x: PAD, y: HUD_TOP, w: availW, h: Math.max(220, availH) };
}
window.addEventListener('resize', layout);

function proj(x, y){
  const s = win.w / cur.view.sw;
  return { x: win.x + (x - cur.view.sx) * s, y: win.y + (y - cur.view.sy) * s };
}

function roundedRectPath(c, x, y, w, h, r){
  c.beginPath();
  c.moveTo(x + r, y); c.arcTo(x + w, y, x + w, y + h, r); c.arcTo(x + w, y + h, x, y + h, r);
  c.arcTo(x, y + h, x, y, r); c.arcTo(x, y, x + w, y, r); c.closePath();
}
function drawPartialRoute(route, frac, color, width, casing){
  const total = route.cum[route.cum.length - 1] * Math.max(0, Math.min(1, frac));
  if (total <= 0) return;
  ctx.beginPath();
  const p0 = proj(route.pts[0][0], route.pts[0][1]);
  ctx.moveTo(p0.x, p0.y);
  for (let i = 1; i < route.pts.length; i++){
    if (route.cum[i] <= total){
      const p = proj(route.pts[i][0], route.pts[i][1]); ctx.lineTo(p.x, p.y);
    } else {
      const seg = route.cum[i] - route.cum[i-1] || 1;
      const t = (total - route.cum[i-1]) / seg;
      const x = route.pts[i-1][0] + (route.pts[i][0]-route.pts[i-1][0]) * t;
      const y = route.pts[i-1][1] + (route.pts[i][1]-route.pts[i-1][1]) * t;
      const p = proj(x, y); ctx.lineTo(p.x, p.y); break;
    }
  }
  ctx.lineJoin = 'round'; ctx.lineCap = 'round';
  if (casing){ ctx.strokeStyle = casing; ctx.lineWidth = width + 4; ctx.stroke(); }
  ctx.strokeStyle = color; ctx.lineWidth = width; ctx.stroke();
}
function drawBadgeAt(route, label, color, dim){
  const m = pointAtFrac(route, 0.5), p = proj(m.x, m.y);
  ctx.globalAlpha = dim ? 0.35 : 1;
  ctx.beginPath(); ctx.arc(p.x, p.y, 15, 0, Math.PI * 2);
  ctx.fillStyle = color; ctx.fill();
  ctx.lineWidth = 3; ctx.strokeStyle = '#fff'; ctx.stroke();
  ctx.fillStyle = '#fff'; ctx.font = '900 15px system-ui,-apple-system,sans-serif';
  ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillText(label, p.x, p.y + 1);
  ctx.globalAlpha = 1;
}
function drawPinAt(x, y, label, fill){
  const p = proj(x, y);
  ctx.beginPath(); ctx.arc(p.x, p.y, 9, 0, Math.PI * 2);
  ctx.fillStyle = fill; ctx.fill();
  ctx.lineWidth = 3; ctx.strokeStyle = '#fff'; ctx.stroke();
  ctx.font = '800 11px system-ui,-apple-system,sans-serif'; ctx.textAlign = 'center'; ctx.textBaseline = 'alphabetic';
  ctx.lineWidth = 4; ctx.strokeStyle = 'rgba(255,255,255,.95)';
  ctx.strokeText(label, p.x, p.y - 15);
  ctx.fillStyle = '#0b0b0b'; ctx.fillText(label, p.x, p.y - 15);
}
function drawRider(route, frac){
  const m = pointAtFrac(route, frac), p = proj(m.x, m.y);
  ctx.save(); ctx.translate(p.x, p.y);
  ctx.beginPath(); ctx.arc(0, 0, 13, 0, Math.PI * 2);
  ctx.fillStyle = '#06C167'; ctx.fill(); ctx.lineWidth = 3; ctx.strokeStyle = '#fff'; ctx.stroke();
  ctx.font = '15px system-ui,sans-serif'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
  ctx.fillText('\uD83D\uDEF5', 0, 0);
  ctx.restore();
}

function draw(ts){
  requestAnimationFrame(draw);
  const dt = Math.min(50, ts - (draw._t || ts)); draw._t = ts;
  ctx.clearRect(0, 0, cssW, cssH);
  if (!cur || !mapReady) return;

  if (shake > 0){ shake = Math.max(0, shake - dt * 0.04); }
  const ox = shake ? (Math.random() - 0.5) * shake : 0;
  const oy = shake ? (Math.random() - 0.5) * shake : 0;
  ctx.save(); ctx.translate(ox, oy);

  roundedRectPath(ctx, win.x, win.y, win.w, win.h, 18);
  ctx.fillStyle = '#f2f4f0'; ctx.fill();
  ctx.save();
  roundedRectPath(ctx, win.x, win.y, win.w, win.h, 18); ctx.clip();
  const v = cur.view;
  ctx.drawImage(mapImg, v.sx, v.sy, v.sw, v.sh, win.x, win.y, win.w, win.h);

  if (state === 'draw'){
    drawT += dt;
    const fA = Math.min(1, drawT / DRAW_MS);
    const fB = Math.min(1, (drawT - DRAW_MS * 0.55) / DRAW_MS);
    drawPartialRoute(cur.A, fA, COL.A, 6.5, 'rgba(255,255,255,.9)');
    if (fB > 0) drawPartialRoute(cur.B, fB, COL.B, 6.5, 'rgba(255,255,255,.9)');
    if (fB >= 1){ state = 'play'; setButtons(true); showPrompt(true); sTick(); }
  } else {
    const dimA = (state === 'reveal' && cur.correct !== 'A') ? 0.28 : 1;
    const dimB = (state === 'reveal' && cur.correct !== 'B') ? 0.28 : 1;
    ctx.globalAlpha = dimA; drawPartialRoute(cur.A, 1, COL.A, 6.5, 'rgba(255,255,255,.9)');
    ctx.globalAlpha = dimB; drawPartialRoute(cur.B, 1, COL.B, 6.5, 'rgba(255,255,255,.9)');
    ctx.globalAlpha = 1;
  }
  drawBadgeAt(cur.A, 'A', COL.A, state === 'reveal' && cur.correct !== 'A');
  drawBadgeAt(cur.B, 'B', COL.B, state === 'reveal' && cur.correct !== 'B');
  const s0 = cur.A.pts[0], s1 = cur.A.pts[cur.A.pts.length - 1];
  drawPinAt(s0[0], s0[1], 'Pick up', '#0b0b0b');
  drawPinAt(s1[0], s1[1], 'Drop off', '#06C167');

  if (state === 'reveal'){
    revealT -= dt;
    const prog = 1 - Math.max(0, revealT) / revealDur;
    drawRider(cur[cur.correct], prog);
    if (revealT <= 0){
      if (lives <= 0){ gameOver(); } else { newRound(); }
    }
  }
  ctx.restore();

  roundedRectPath(ctx, win.x, win.y, win.w, win.h, 18);
  ctx.lineWidth = 3.5; ctx.strokeStyle = '#c3d92e'; ctx.stroke();

  if (state === 'play'){
    timeLeft -= dt;
    if (timeLeft <= 0){ timeLeft = 0; resolve('timeout'); }
    const f = document.getElementById('timerfill');
    if (f) f.style.width = Math.round(100 * timeLeft / timeMax) + '%';
  }

  for (let i = popups.length - 1; i >= 0; i--){
    const p = popups[i]; p.t += dt;
    if (p.t > 900){ popups.splice(i, 1); continue; }
    ctx.globalAlpha = 1 - p.t / 900;
    ctx.font = '900 ' + p.size + 'px system-ui,sans-serif';
    ctx.textAlign = 'center'; ctx.textBaseline = 'alphabetic';
    ctx.lineWidth = 6; ctx.strokeStyle = 'rgba(255,255,255,.9)';
    ctx.strokeText(p.text, cssW / 2, win.y + win.h * 0.42 - p.t * 0.04);
    ctx.fillStyle = p.color; ctx.fillText(p.text, cssW / 2, win.y + win.h * 0.42 - p.t * 0.04);
    ctx.globalAlpha = 1;
  }
  for (let i = particles.length - 1; i >= 0; i--){
    const p = particles[i]; p.t += dt;
    if (p.t > p.life){ particles.splice(i, 1); continue; }
    p.x += p.vx * dt; p.y += p.vy * dt; p.vy += 0.0011 * dt;
    ctx.globalAlpha = 1 - p.t / p.life;
    ctx.fillStyle = p.col; ctx.fillRect(p.x, p.y, p.s, p.s);
    ctx.globalAlpha = 1;
  }
  if (flash){
    ctx.fillStyle = flash.color.replace('A', String(flash.a));
    ctx.fillRect(0, 0, cssW, cssH);
    flash.a -= dt * 0.0009; if (flash.a <= 0) flash = null;
  }

  if (DEBUG && cur){
    ctx.font = '700 11px monospace'; ctx.textAlign = 'left'; ctx.fillStyle = '#000';
    const la = Math.round(cur.A.cum[cur.A.cum.length-1]), lb = Math.round(cur.B.cum[cur.B.cum.length-1]);
    ctx.fillText('band ' + cur.band + ' A=' + la + ' B=' + lb + ' correct=' + cur.correct + ' t=' + Math.round(timeLeft), win.x + 8, win.y + win.h - 10);
  }
  ctx.restore();
}
requestAnimationFrame(draw);

function spawnParticles(){
  for (let i = 0; i < 26; i++){
    particles.push({ x: cssW / 2, y: win.y + win.h * 0.4, vx: (Math.random() - 0.5) * 0.55,
      vy: -Math.random() * 0.5 - 0.1, s: 4 + Math.random() * 5, t: 0, life: 700 + Math.random() * 500,
      col: ['#06C167', '#ffd24a', '#ffffff', '#ff5e5b'][i % 4] });
  }
}
function resolve(kind){
  if (state !== 'play') return;
  const good = (kind === cur.correct);
  stats.answers++;
  if (kind !== 'timeout'){ stats.picks++; stats.rtSum += (timeMax - timeLeft); }
  if (good) stats.correct++;
  if (good){
    const ROUND_BASE = 30, SPEED_BONUS = 30;
    const speedFrac = Math.max(0, Math.min(1, timeLeft / timeMax));
    const add = ROUND_BASE + Math.round(SPEED_BONUS * speedFrac);
    score += add;
    streak++;
    if (streak > bestStreak){ bestStreak = streak; localStorage.setItem('routerush_beststreak', bestStreak); }
    lastResult = 'ok'; revealT = REVEAL_OK;
    flash = { color: 'rgba(1,145,71,A)', a: 0.24 };
    sOK(); buzz(15); if (!reduceMotion) spawnParticles();
    popups.push({ text: '+' + add, color: COL.good, size: 34, t: 0 });
    if (score > best){ best = score; localStorage.setItem('routerush_best_v2', best); }
  } else {
    streak = 0;
    lives = Math.max(0, lives - 1);
    lastResult = (kind === 'timeout') ? 'timeout' : 'bad';
    revealT = REVEAL_BAD;
    flash = { color: 'rgba(255,77,77,A)', a: 0.3 };
    shake = reduceMotion ? 0 : 13;
    sBad(); buzz([40, 30, 40]);
    popups.push({ text: kind === 'timeout' ? 'TOO SLOW' : 'WRONG', color: COL.bad, size: 30, t: 0 });
  }
  revealDur = revealT;
  chosen = kind;
  state = 'reveal';
  setButtons(false); showPrompt(false);
  updateHUD();
}
function choose(label){ if (state === 'play') resolve(label); }

function gameOver(){
  state = 'over';
  document.body.classList.remove('playing');
  setButtons(false); showPrompt(false);
  const isBest = score > 0 && score >= best;
  if (score > best){ best = score; localStorage.setItem('routerush_best_v2', best); }
  try { window.parent.postMessage({ type: 'gigScore', score: score }, '*'); } catch (e) {}
  ga('pathpicker_complete', { score: score });
  document.getElementById('newbest').classList.toggle('show', isBest);
  const acc = stats.answers ? Math.round(stats.correct / stats.answers * 100) : 0;
  const avgRt = stats.picks ? (stats.rtSum / stats.picks / 1000).toFixed(2) + 's' : '-';
  const nStars = acc >= 85 ? 3 : acc >= 60 ? 2 : acc >= 35 ? 1 : 0;
  document.getElementById('stars').textContent = '\u2605'.repeat(nStars) + '\u2606'.repeat(3 - nStars);
  document.getElementById('overStats').innerHTML =
    '<div class="bigscore">' + score + '</div>' +
    '<div class="substat">Routes delivered: <b>' + stats.correct + '</b> &middot; Accuracy: <b>' + acc + '%</b> &middot; Avg pick: <b>' + avgRt + '</b></div>';
  showOnlyOverlay('over');
}

function updateHUD(){
  let bags = '';
  for (let i = 0; i < 3; i++) bags += '<img class="life-bag' + (i < lives ? '' : ' dead') + '" src="uber-bag.png" alt="life">';
  document.getElementById('lives').innerHTML = bags;
  document.getElementById('score').textContent = score;
  document.getElementById('round').textContent = round || 1;
  document.getElementById('best').textContent = best;
  document.getElementById('streak').textContent = streak;
}
function setButtons(on){
  document.getElementById('btnA').classList.toggle('disabled', !on);
  document.getElementById('btnB').classList.toggle('disabled', !on);
}
function showPrompt(on){ document.getElementById('prompt').classList.toggle('show', on); }

document.getElementById('btnA').addEventListener('click', function(){ choose('A'); });
document.getElementById('btnB').addEventListener('click', function(){ choose('B'); });
canvas.addEventListener('pointerdown', function(e){
  if (state !== 'play') return;
  const r = canvas.getBoundingClientRect();
  const x = e.clientX - r.left, y = e.clientY - r.top;
  let bestLbl = null, bestD = 24;
  ['A', 'B'].forEach(function(lbl){
    const route = cur[lbl];
    for (let i = 1; i < route.pts.length; i++){
      const p1 = proj(route.pts[i-1][0], route.pts[i-1][1]), p2 = proj(route.pts[i][0], route.pts[i][1]);
      const dx = p2.x - p1.x, dy = p2.y - p1.y;
      const L2 = dx*dx + dy*dy || 1;
      const t = Math.max(0, Math.min(1, ((x - p1.x) * dx + (y - p1.y) * dy) / L2));
      const d = Math.hypot(x - (p1.x + dx * t), y - (p1.y + dy * t));
      if (d < bestD){ bestD = d; bestLbl = lbl; }
    }
  });
  if (bestLbl) choose(bestLbl);
});

let actx = null;
function ac(){ if (!actx){ try { actx = new (window.AudioContext || window.webkitAudioContext)(); } catch (e) {} } if (actx && actx.state === 'suspended') actx.resume(); return actx; }
function tone(freq, dur, type, gain, when){
  const c = ac(); if (!c || muted) return;
  const o = c.createOscillator(), g = c.createGain();
  const t = c.currentTime + (when || 0);
  o.type = type || 'sine'; o.frequency.value = freq;
  g.gain.setValueAtTime(0.0001, t);
  g.gain.exponentialRampToValueAtTime(gain || 0.08, t + 0.015);
  g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
  o.connect(g).connect(c.destination); o.start(t); o.stop(t + dur + 0.05);
}
function sOK(){ tone(660, 0.16, 'triangle', 0.09); tone(880, 0.22, 'triangle', 0.08, 0.09); }
function sBad(){ tone(220, 0.25, 'sawtooth', 0.07); tone(160, 0.3, 'sawtooth', 0.06, 0.1); }
function sTick(){ tone(1180, 0.06, 'square', 0.03); }
function buzz(p){ try { if (navigator.vibrate) navigator.vibrate(p); } catch (e) {} }
const muteBtn = document.getElementById('muteBtn');
function syncMute(){ muteBtn.textContent = muted ? '\uD83D\uDD07' : '\uD83D\uDD0A'; }
muteBtn.addEventListener('click', function(){ muted = !muted; localStorage.setItem('pathpicker_muted', muted ? '1' : '0'); syncMute(); });
syncMute();

let htTimer = null;
function drawHowto(){
  const cv = document.getElementById('htMap'); if (!cv || !mapReady) return;
  const c2 = cv.getContext('2d');
  const rd = LIB.E[0];
  const all = rd.short.concat(rd.long);
  let x0 = Math.min.apply(null, all.map(p => p[0])) - 50, x1 = Math.max.apply(null, all.map(p => p[0])) + 50;
  let y0 = Math.min.apply(null, all.map(p => p[1])) - 50, y1 = Math.max.apply(null, all.map(p => p[1])) + 50;
  const W = cv.width, H = cv.height, AR = W / H;
  let w = x1 - x0, h = y1 - y0;
  if (w / h > AR){ const nh = w / AR; y0 -= (nh - h) / 2; h = nh; } else { const nw = h * AR; x0 -= (nw - w) / 2; w = nw; }
  c2.clearRect(0, 0, W, H);
  c2.drawImage(mapImg, x0, y0, w, h, 0, 0, W, H);
  [[rd.long, COL.B], [rd.short, COL.A]].forEach(function(pair){
    const pts = pair[0], col = pair[1];
    c2.beginPath();
    const p0 = { x: (pts[0][0] - x0) / w * W, y: (pts[0][1] - y0) / h * H };
    c2.moveTo(p0.x, p0.y);
    for (let i = 1; i < pts.length; i++) c2.lineTo((pts[i][0] - x0) / w * W, (pts[i][1] - y0) / h * H);
    c2.lineJoin = 'round'; c2.lineCap = 'round';
    c2.strokeStyle = 'rgba(255,255,255,.9)'; c2.lineWidth = 8; c2.stroke();
    c2.strokeStyle = col; c2.lineWidth = 5; c2.stroke();
  });
}
function startHowtoAnim(){
  clearInterval(htTimer);
  let flip = false;
  htTimer = setInterval(function(){
    flip = !flip;
    const a = document.getElementById('htBtnA'), b = document.getElementById('htBtnB');
    if (a) a.classList.toggle('pick', flip);
    if (b) b.classList.toggle('pick', !flip);
    drawHowto();
  }, 900);
  drawHowto();
}
function stopHowtoAnim(){ clearInterval(htTimer); }
mapImg.addEventListener('load', drawHowto);

function startGame(){
  score = 0; lives = 3; streak = 0; round = 0;
  stats = { answers: 0, correct: 0, rtSum: 0, picks: 0 };
  document.body.classList.add('playing');
  document.querySelectorAll('.overlay').forEach(function(o){ o.classList.add('hidden'); });
  layout();
  ga('pathpicker_start', {});
  newRound();
}
document.getElementById('howtoPlay').addEventListener('click', function(){ stopHowtoAnim(); startGame(); });
document.getElementById('againBtn').addEventListener('click', startGame);

layout();
updateHUD();
startHowtoAnim();

if (DEBUG){
  window.__rp = { choose: choose, resolve: resolve,
    get cur(){ return cur; }, get state(){ return state; },
    get score(){ return score; }, get lives(){ return lives; }, set lives(v){ lives = v; } };
}

"""
engine = engine.replace("__LIB__", json.dumps(lib, separators=(",", ":")))
io.open(GAME, "w", encoding="utf-8").write(head + engine + tail)
print("spliced ok, new size:", len(head) + len(engine) + len(tail))
